### ISSUE TITLE
clarify compound condition in analyzeCells

### ISSUE THREAD

**Issue by jspaaks** [NLeSC/enram#88]
currently like this:
```
// determine which cells to drop from map based on low mean dBZ / high stdev /
// small area / high percentage clutter
for (iCell = 0; iCell < nCells; iCell++) {
    if (cellProp[iCell].nGates < nGatesCellMin ||
        (cellProp[iCell].dbzAvg < cellDbzMin &&
         cellProp[iCell].texAvg > cellStdDevMax &&
         ((float) cellProp[iCell].nGatesClutter / cellProp[iCell].nGates) < cellClutterFractionMax )) { // FIXME this condition still looks wrong if you ask me
        // Terms 2,3 and 4 are combined with && to be conservative in labeling stuff as
        // bird migration --see discussion of issue #37 on GitHub.
        cellProp[iCell].drop = TRUE;
        cellProp[iCell].nGates = 0;
    }
}
```

should be more or less like this
```
if (cellProp[iCell].dbzAvg < cellDbzMin && cellProp[iCell].texAvg > cellStdDevMax
   if cellProp[iCell].clutterArea / cellProp[iCell].area) < cellClutterFraction
        drop the cell
   else
        do not drop the cell
   endif
endif
```

**Comment by jspaaks** [comment]
@adokter could you verify [this](https://github.com/NLeSC/enram/blob/68303a8cb91b3c2a1280a528c43d233c215ee6f7/ncradar/lib/vol2bird/libvol2bird.c#L535-L571) section

**Comment by adokter** [comment]
Ok, but the variable name `tooMuchClutter` is misleading, I would rename it to `LimitedClutter`, because the parameter is TRUE when the amount of clutter is below a certain threshold.

We need to test for the clutter fraction, because I do not want to assign blobs as birds when clutter contamination is high - we might then be dealing with a clutter blob instead of blob of birds.

**Comment by jspaaks** [comment]
I changed the sign in the comparison and moved the if statement body to a new else clause.
